files:
  - source: /locales/en/*.js
    translation: /locales/%two_letters_code%/%original_file_name%
  - source: /locales/en/l10n-*.js
    translation: /locales/%two_letters_code%/%original_file_name%
